import { requireStore } from "@/lib/current-store";
import { adjustStock, createIngredient } from "./actions";

const units:Record<string,string>={unit:"un",g:"g",kg:"kg",ml:"ml",l:"L",package:"pacote"};
export default async function Page({searchParams}:{searchParams:Promise<{erro?:string;sucesso?:string}>}){
  const params=await searchParams;const {supabase,store}=await requireStore();
  const [{data:ingredients},{data:movements}]=await Promise.all([
    supabase.from("ingredients").select("*").eq("store_id",store.id).order("name"),
    supabase.from("stock_movements").select("id,quantity,movement_type,notes,created_at,ingredients(name,unit)").eq("store_id",store.id).order("created_at",{ascending:false}).limit(12),
  ]);
  return <div className="page"><header className="page-head"><div><span>ESTOQUE</span><h1>Ingredientes e insumos</h1><p>Entradas, perdas, inventário e níveis mínimos.</p></div></header>
    {params.erro?<div className="flash error">{params.erro}</div>:null}{params.sucesso?<div className="flash">{params.sucesso}</div>:null}
    <section className="ops-grid"><div className="ops-stack"><article className="surface"><div className="section-head"><h2>Posição atual</h2><span className="muted">{ingredients?.length??0} itens</span></div><table className="data-table"><thead><tr><th>Ingrediente</th><th>Atual</th><th>Mínimo</th><th>Custo médio</th></tr></thead><tbody>{ingredients?.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>{units[i.unit]??i.unit}</small></td><td className={Number(i.current_stock)<=Number(i.minimum_stock)?"stock-low":"stock-ok"}>{Number(i.current_stock)} {units[i.unit]??i.unit}</td><td>{Number(i.minimum_stock)}</td><td>{Number(i.average_cost).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</td></tr>)}</tbody></table>{!ingredients?.length?<p className="muted">Nenhum ingrediente cadastrado.</p>:null}</article>
      <article className="surface"><h2>Últimas movimentações</h2><table className="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Quantidade</th><th>Observação</th></tr></thead><tbody>{movements?.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString("pt-BR")}</td><td>{m.movement_type}</td><td>{Number(m.quantity)}</td><td>{m.notes}</td></tr>)}</tbody></table></article></div>
      <aside className="ops-stack"><article className="surface"><h2>Novo ingrediente</h2><form action={createIngredient} className="compact-form"><label>Nome<input name="name" required/></label><label>Unidade<select name="unit"><option value="unit">Unidade</option><option value="g">Gramas</option><option value="kg">Quilos</option><option value="ml">Mililitros</option><option value="l">Litros</option><option value="package">Pacote</option></select></label><label>Estoque inicial<input name="current_stock" type="number" step="0.001" defaultValue="0"/></label><label>Estoque mínimo<input name="minimum_stock" type="number" step="0.001" defaultValue="0"/></label><label>Custo médio<input name="average_cost" type="number" step="0.0001" defaultValue="0"/></label><button className="button primary">Cadastrar</button></form></article>
      <article className="surface"><h2>Movimentar estoque</h2><form action={adjustStock} className="compact-form"><label>Ingrediente<select name="ingredient_id" required><option value="">Selecione</option>{ingredients?.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Operação<select name="movement_type"><option value="purchase">Entrada/compra</option><option value="waste">Perda</option><option value="internal_use">Uso interno</option></select></label><label>Quantidade<input name="quantity" type="number" step="0.001" min="0.001" required/></label><label>Observação<input name="notes"/></label><button className="button primary">Registrar</button></form></article></aside></section>
  </div>;
}
